contract:
  ctAddr: "************************************"  #合约地址
  startAddr:  "************************************"   #顶级节点地址
  sendAddr:  "************************************"   #授权地址
  sendAddrPk:  "************************************"  
  gasPrice: 5000000000 # Gas Price越高，交易优先级越高，打包交易速度越快。
  gasLimit: 1500000  # Gas Limit 是用户愿意为执行某个操作或确认交易支付的最大Gas量（最少21,000）
  isAddGas: false #是否启用按当前市价进行加权矿工费用
  addGas:   2000000000 #所增加费用
  url: "https://mainnet.infura.io/d75c50732022222222222222222222" #正式网 or 测试网
